// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Support both local DATABASE_URL and Vercel Postgres POSTGRES_PRISMA_URL
const databaseUrl = process.env["DATABASE_URL"] || process.env["POSTGRES_PRISMA_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
